.TH GNU Freetalk "1" "May 2014" "freetalk 4.0" "User Commands"
.SH NAME
GNU freetalk \- A console based Jabber client
.SH SYNOPSIS
.B freetalk
[\fIOPTION\fR...]
.SH DESCRIPTION
Freetalk is a console based jabber client/bot with a readline interface and
guile extensions
.TP
\fB\-j\fR, \fB\-\-jid\fR=\fIJABBERID\fR
user@domain Jabber ID
.TP
\fB\-s\fR, \fB\-\-script\fR=\fISCRIPTFILE\fR
Freetalk script
.TP
\-?, \fB\-\-help\fR
Give this help list
.TP
\fB\-\-usage\fR
Give a short usage message
.TP
\fB\-V\fR, \fB\-\-version\fR
Print program version
.PP
Mandatory or optional arguments to long options are also mandatory or optional
for any corresponding short options.
.SH "REPORTING BUGS"
Report bugs at https://github.com/GNUFreetalk/freetalk/issues
.SH "SEE ALSO"
The full documentation for
.B freetalk
is maintained as a Texinfo manual.  If the
.B info
and
.B freetalk
programs are properly installed at your site, the command
.IP
.B info freetalk
.PP
should give you access to the complete manual.
